version: "3"

services: 
     
  db:
    image: mariadb:latest
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: reidb  
      #MYSQL_USER: reibegaj
      #MYSQL_PASSWORD: reidatabase
    volumes:
      - "./maria-data:/var/lib/mysql"
  web:
      image: phpmyadmin:latest
      ports:
         - "80:80"
      environment:
        MYSQL_ROOT_PASSWORD: reidb
        PMA_HOST: mariadb-server
        PMA_USER: root
        PMA_PASSWORD: reidb

  app:
      build:
        context: ./app
        dockerfile: ../Dockerfile
      environment:
         DB_USER: "root"
         DB_PASS: "reidb"
         DB_HOST: "db"
         DB_NAME: "Rei's DB" 
